<?php

/**
*
*Implementing hook_permission()
*
*/
function cronmonitor_permission() {
  return array(
    'administer cronmonitor' => array(
      'title' => t('Administer Cron Monitor'),
      'description' => t('Perform administration tasks for Cron Monitor .'),
    ),
  );
}

/***
*
**Implementing hook_menu() 
*/

function cronmonitor_menu() {
    $items['admin/config/cronmonitor'] = array(
  	'title' => 'Cron Monitor Settings',
  	'type' => MENU_NORMAL_ITEM,
  	'page callback' => 'drupal_get_form',
	'page arguments' => array('cronmonitor_admin_form'),
	'access arguments' => array('administer cronmonitor'),
    );
    return $items;
  }

/**
*
*Administration form for Cron Monitor()
*
*/
function cronmonitor_admin_form($form,&$form_state){
    $form['cronmonitor_enable'] = array(
  	'#type' =>'checkbox', 
    	'#title' => t('Enable Cron Monitor.'),
	'#default_value' => variable_get('cronmonitor_enable',0),
    );

    $form['cronmonitor_email_text'] = array(
	'#title' => t('Text to send with Cron Monitor Emails'),
	'#type' => 'textarea',
	'#description' => t('Enter some text to send with cron monitor email message'),

	'#default_value' =>  variable_get('cronmonitor_email_text',''),
	);


    return system_settings_form($form);  
}

/****
*
*
*Implementing hook_cron()
*/

function cronmonitor_cron() {
  if(variable_get('cronmonitor_enable',0)){
  //send cron monitor email at periodic interval.
	drupal_mail('cronmonitor','cronmonitor_email','technical.partha@gmail.com',language_default());
  }
}

/***
*
*Implementing hook_mail()
*
*/


function cronmonitor_mail($key, &$message, $params) {
   switch ($key){
    case 'cronmonitor_mail':
	$message['subject'] = t('This is a cron monitor report');
	$message['body'][] = t('This is a report from cron monitor on GradeManagement System',array('GradeManagement System' => variable_get('GradeManagement System','GradeManagement System')));
	$message['body'][] = t(variable_get('cronmonitor_email_text',''));
	
	break;
   }
}






